### PR TITLE
Sztab-WOSP-Bialystok/wosp-staff-issues#24

### PR DESCRIPTION
**Pull request by TheUnDc**

### CODE REVIEW

**Review by Freesebee — APPROVED** [review]
❤️

**Review by Freesebee — DISMISSED** [review]
Code doesn't compile 😢 
image

**Comment by TheUnDc** [comment]
I recommend separate link property from Navigations object to antoher array. Links in dropdown feature elements objects are detected as undefinded

**Review by Freesebee — APPROVED** [review]

**Comment by Freesebee** [comment]
> I recommend separate link property from Navigations object to antoher array. Links in dropdown feature elements objects are detected as undefinded

Will create another Issuer for that

**Pull request merged**
